version: "3.8"

services: 
  app: 
    container_name: imli-client-prod
    image: docker-react-prod-i
    build:
      dockerfile: Dockerfile.prod
    ports: 
      - "8080:80"
    environment:
      - NODE_ENV=production