version: "3.8"
services:
  imli-api:
    build: ../app-imli-server
    container_name: imli-api
    ports:
      - "4000:4000"
    volumes:
      - ../app-imli-server:/api
    command: sh -c "yarn && yarn dev:docker"
  imli-client:
    build: ./
    depends_on:
      - imli-api
    container_name: imli-client
    ports:
      - "3000:3000"
    volumes:
      - ./:/client/
    entrypoint: ./wait-for-it.sh imli-api:4000 -- sh -c "yarn && yarn start"