services:
  imli-api:
    build: ../app-imli-server
    environment:
      NODE_DATABASE_URL: 'mongodb://imli-db:27017/imli'
    ports:
      - "4000:4000"
    volumes:
      - ../app-imli-server:/api
    depends_on:
      - imli-db
    command: sh -c "yarn && yarn dev:docker"
    healthcheck:
      test: "curl --fail http://localhost:4000/health || exit 1"
      timeout: 15s
      retries: 5
  imli-client:
    build: ./
    depends_on:
      imli-api:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app-imli-client
      - ./node_modules:/app-imli-client/node_modules
    entrypoint: sh -c "yarn && yarn start"
  imli-db:
    image: mongo:latest
    volumes:
      - mongoDb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=imli
    restart: always
    ports:
      - "27017:27017"

volumes:
  mongoDb: {}